version: '3.8'

services:
  app:
    image: crpi-98ymlx0yqe646pye.cn-guangzhou.personal.cr.aliyuncs.com/myq-space/langrissar-server:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=langrissar
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "npm run migration:run && node dist/src/main.js"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: